CREATE DATABASE IF NOT EXISTS BD_REDE_SOCIAL;
USE BD_REDE_SOCIAL;

CREATE TABLE IF NOT EXISTS USUARIOS(
	ID INT AUTO_INCREMENT PRIMARY KEY, 
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(500) NOT NULL,
    BIO VARCHAR (150),
    FOTO BLOB
);
CREATE TABLE IF NOT EXISTS PUBLICACOES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    FOTO BLOB NOT NULL,
    DESCRICAO VARCHAR(1440),
    DATA_PUBLICACAO DATE NOT NULL,
    FK_USUARIO_ID INT ,
    FOREIGN KEY(FK_USUARIO_ID) REFERENCES USUARIOS(ID)
);