CREATE DATABASE IF NOT EXISTS BD_SUPER_MERCADO;
USE BD_SUPER_MERCADO;

CREATE TABLE IF NOT EXISTS CONSUMIDOR(
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_BARRAS VARCHAR(20) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    PESO DOUBLE,
    QUANTIDADE INT NOT NULL DEFAULT(0),
    PRECO DOUBLE NOT NULL,
    DATA_VALIDADE DATE
);

CREATE TABLE IF NOT EXISTS SUPERMERCADO(
	CNPJ VARCHAR(14) PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(100),
    TELEFONE VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    LOGRADOURO VARCHAR(50) NOT NULL,
    NUMERO VARCHAR(10),
    CIDADE VARCHAR(10) NOT NULL,
    ESTADO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CARTEIRA_TRABALHO BLOB,
    BANCO_AGENCIA VARCHAR(10),
    BANCO_CONTA VARCHAR(10),
    DATA_ADMISSAO DATE,
    JORNADA_TRABALHO VARCHAR(100),
    FK_SUPERMERCADO_CNPJ VARCHAR(14),
    FOREIGN KEY (FK_SUPERMERCADO_CNPJ) REFERENCES SUPERMERCADO(CNPJ)
);

CREATE TABLE IF NOT EXISTS PRODUTO_CONSUMIDOR(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_PRODUTO_ID INT,
    FK_CONSUMIDOR_CPF VARCHAR(11),
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTOS(ID),
    FOREIGN KEY (FK_CONSUMIDOR_CPF) REFERENCES CONSUMIDOR(CPF)
);

CREATE TABLE IF NOT EXISTS SUPERMERCADO_PRODUTOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_SUPERMERCADO_CNPJ VARCHAR(14),
    FK_PRODUTO_ID INT,
    FOREIGN KEY (FK_SUPERMERCADO_CNPJ) REFERENCES SUPERMERCADO(CNPJ),
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTOS(ID)
    
);